services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: extra-php:8.2-gd
    container_name: extra_php
    command: ["php-fpm"]
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: extra
      DB_USER: extra
      DB_PASS: extra123
      COMPOSER_HOME: /tmp/.composer  # 1. Защита от ошибок прав кэша Composer

  nginx:
    image: nginx:latest
    container_name: extra_nginx
    ports:
      - "80:80" 
    depends_on:
      - php
    volumes:
      - ./:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mariadb:11
    container_name: extra_mariadb
    # 2. Платформа linux/amd64 гарантирует стабильную работу MariaDB на Apple Silicon Mac
    platform: linux/amd64  
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: extra
      MARIADB_USER: extra
      MARIADB_PASSWORD: extra123
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: extra_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root123

volumes:
  db_data:

